name: christmas
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  flutter_html_to_pdf: ^0.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  just_audio: ^0.9.42
  provider: ^6.1.2
  simple_animations: ^4.2.0
  snow_fall_animation: ^0.0.1+3
  snowfall: ^0.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/christmas.mp3
